# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'rare/ui/components/tabs/games/game_info/cloud_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_cloud_widget(object):
    def setupUi(self, cloud_widget):
        cloud_widget.setObjectName("cloud_widget")
        cloud_widget.resize(400, 300)
        self.horizontalLayout = QtWidgets.QHBoxLayout(cloud_widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.local_gb = QtWidgets.QGroupBox(cloud_widget)
        self.local_gb.setObjectName("local_gb")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.local_gb)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.date_info_local = QtWidgets.QLabel(self.local_gb)
        self.date_info_local.setText("TextLabel")
        self.date_info_local.setAlignment(QtCore.Qt.AlignCenter)
        self.date_info_local.setObjectName("date_info_local")
        self.verticalLayout_2.addWidget(self.date_info_local)
        self.icon_local = QtWidgets.QLabel(self.local_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_local.sizePolicy().hasHeightForWidth())
        self.icon_local.setSizePolicy(sizePolicy)
        self.icon_local.setText("")
        self.icon_local.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_local.setObjectName("icon_local")
        self.verticalLayout_2.addWidget(self.icon_local)
        self.upload_button = QtWidgets.QPushButton(self.local_gb)
        self.upload_button.setObjectName("upload_button")
        self.verticalLayout_2.addWidget(self.upload_button)
        self.horizontalLayout.addWidget(self.local_gb)
        self.cloud_gb = QtWidgets.QGroupBox(cloud_widget)
        self.cloud_gb.setObjectName("cloud_gb")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.cloud_gb)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.date_info_remote = QtWidgets.QLabel(self.cloud_gb)
        self.date_info_remote.setText("TextLabel")
        self.date_info_remote.setAlignment(QtCore.Qt.AlignCenter)
        self.date_info_remote.setObjectName("date_info_remote")
        self.verticalLayout_3.addWidget(self.date_info_remote)
        self.icon_remote = QtWidgets.QLabel(self.cloud_gb)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.icon_remote.sizePolicy().hasHeightForWidth())
        self.icon_remote.setSizePolicy(sizePolicy)
        self.icon_remote.setText("")
        self.icon_remote.setAlignment(QtCore.Qt.AlignCenter)
        self.icon_remote.setObjectName("icon_remote")
        self.verticalLayout_3.addWidget(self.icon_remote)
        self.download_button = QtWidgets.QPushButton(self.cloud_gb)
        self.download_button.setObjectName("download_button")
        self.verticalLayout_3.addWidget(self.download_button)
        self.horizontalLayout.addWidget(self.cloud_gb)

        self.retranslateUi(cloud_widget)
        QtCore.QMetaObject.connectSlotsByName(cloud_widget)

    def retranslateUi(self, cloud_widget):
        _translate = QtCore.QCoreApplication.translate
        cloud_widget.setWindowTitle(_translate("cloud_widget", "Form"))
        self.local_gb.setTitle(_translate("cloud_widget", "Local"))
        self.upload_button.setText(_translate("cloud_widget", "Upload"))
        self.cloud_gb.setTitle(_translate("cloud_widget", "Cloud"))
        self.download_button.setText(_translate("cloud_widget", "Download"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    cloud_widget = QtWidgets.QWidget()
    ui = Ui_cloud_widget()
    ui.setupUi(cloud_widget)
    cloud_widget.show()
    sys.exit(app.exec_())
